bjorncrm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('interactions/', include('interaction.urls', namespace="interactions")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('xxxx/', TemplateView.as_view(template_name="layout_fixed.html")),
]

contacts/urls.py
from django.contrib import admin
from django.urls import path

from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.home, name='home'),
    path(r'contato/api/', views.ContatoApiList.as_view(), name='contato-api-list'),
    path(r'contato/api/<int:pk>/', views.ContatoApiDetail.as_view(), name='contato-api-details'),

    path(r'contato/', views.ContatoList.as_view(), name='contato-list'),
    path(r'contato/add/', views.ContatoCreate.as_view(), name='contato-create'),
    path(r'contato/update/<int:pk>/', views.ContatoUpdate.as_view(), name='contato-update'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name="dashboard/dashboard.html"), name='index'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = 'users'

urlpatterns = [
    # path(r'list/', views.UserList.as_view(), name='users-list'),
    # path(r'users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    # path(r'users/add/', views.UserCreate.as_view(), name='user-create'),
    # path(r'users/update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    # path('login', TemplateView.as_view(template_name='users/login_simple.html'))
    path(r'users/signup/', views.signup, name='signup'),
]

contacts/models.py
from django.db import models
from django.contrib.auth.models import User


class Contato(models.Model):
    TIPO_CONTATO = (
        ('P', 'Pessoal'),
        ('C', 'Comercial'),
    )

    nome = models.CharField(max_length=100, verbose_name='Nome')
    ocupacao = models.CharField(max_length=50, blank=True, null=True, verbose_name='Ocupação')
    tipo = models.CharField(choices=TIPO_CONTATO, max_length=1, verbose_name='Tipo')
    instituicao = models.CharField(max_length=50, blank=True, null=True, verbose_name='Instituição')
    departamento = models.CharField(max_length=50, blank=True, null=True, verbose_name='Departamento')
    notas = models.TextField(blank=True, verbose_name='Notas')


class Endereco(models.Model):
    pais = models.CharField(max_length=50, blank=True, null=True, verbose_name='País')
    estado = models.CharField(max_length=30, blank=True, null=True, verbose_name='Estado')
    cidade = models.CharField(max_length=50, blank=True, null=True, verbose_name='Cidade')
    logradouro = models.CharField(max_length=100, blank=True, null=True, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, blank=True, null=True, verbose_name='Número')
    complemento = models.CharField(max_length=10, blank=True, null=True, verbose_name='Complemento')
    cep = models.CharField(max_length=9, blank=True, null=True, verbose_name='CEP')


class Telefone(models.Model):
    numero = models.CharField(max_length=20, blank=True, verbose_name='Telefone')


class Email(models.Model):
    email = models.EmailField(blank=True, verbose_name="E-mail")


class ContatoEndereco(models.Model):
    contato = models.ForeignKey(Contato, on_delete=models.CASCADE)
    endereco = models.ForeignKey(Endereco, on_delete=models.CASCADE)
    #tipo = Residencial, Comercial, Outro


class ContatoTelefone(models.Model):
    contato = models.ForeignKey(Contato, on_delete=models.CASCADE)
    telefone = models.ForeignKey(Telefone, on_delete=models.CASCADE)


class ContatoEmail(models.Model):
    contato = models.ForeignKey(Contato, on_delete=models.CASCADE)
    email = models.ForeignKey(Email, on_delete=models.CASCADE)


# class Notas(models.Model):
#     usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
#     timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)
#     texto = models.TextField(verbose_name='Nota')

contacts/forms.py
from django.forms import ModelForm, BaseFormSet, formset_factory
from contacts import models # import Contato, Email, Telefone, Endereco


class ContatoForm(ModelForm):
    class Meta:
        model = models.Contato
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class EmailForm(ModelForm):
    class Meta:
        model = models.Email
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class TelefoneForm(ModelForm):
    class Meta:
        model = models.Telefone
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class EnderecoForm(ModelForm):
    class Meta:
        model = models.Endereco
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


TelefoneFormSet = formset_factory(
    TelefoneForm, can_delete=True, min_num=3)


EmailFormSet = formset_factory(
    EmailForm, can_delete=True, min_num=2)

contacts/views.py
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

# from rest_framework import status
# from rest_framework.decorators import api_view
# from rest_framework.parsers import JSONParser
# from rest_framework.renderers import JSONRenderer
# from rest_framework.response import Response
from rest_framework import generics

from contacts.forms import ContatoForm, TelefoneFormSet, EmailFormSet, EnderecoForm
from contacts.models import Contato, ContatoEndereco, ContatoTelefone, ContatoEmail
from contacts.serializers import ContatoSerializer, TelefoneSerializer


@login_required
def home(request):
    return render(request, 'contacts/index.html')


class ContatoApiList(generics.ListCreateAPIView):
    queryset = Contato.objects.all()
    serializer_class = ContatoSerializer


class ContatoApiDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Contato.objects.all()
    serializer_class = ContatoSerializer


class ContatoList(ListView):
    model = Contato


class ContatoCreate(CreateView):
    template_name = 'contacts/contact_create_update.html'
    form_class = ContatoForm
    success_url = reverse_lazy('contacts:contato-list')

    def get_context_data(self, **kwargs):
        context = super(ContatoCreate, self).get_context_data(**kwargs)
        context['form_endereco'] = EnderecoForm()
        context['formset_telefone'] = TelefoneFormSet()
        context['formset_email'] = EmailFormSet()
        return context

    def form_valid(self, form):
        save_ok = True

        with transaction.atomic():
            response = super(ContatoCreate, self).form_valid(form)
            endereco_form = EnderecoForm(self.request.POST)
            telefones_formset = TelefoneFormSet(self.request.POST)
            emails_formset = EmailFormSet(self.request.POST)

            if endereco_form.is_valid():
                endereco_obj = endereco_form.save()
                inst = ContatoEndereco(contato=self.object, endereco=endereco_obj)
                inst.save()
            else:
                save_ok = False
                print('E', endereco.errors)

            if telefones_formset.is_valid():
                for telefone_form in telefones_formset.forms:
                    telefone_obj = telefone_form.save()
                    inst = ContatoTelefone(contato=self.object, telefone=telefone_obj)
                    inst.save()
            else:
                save_ok = False
                print('E', telefones.errors)

            if emails_formset.is_valid():
                for email_form in emails_formset.forms:
                    email_obj = email_form.save()
                    inst = ContatoEmail(contato=self.object, email=email_obj)
                    inst.save()
            else:
                save_ok = False
                print('E', emails.errors)


        if not save_ok:
            return 'error'

        return response


class ContatoUpdate(UpdateView):
    template_name = 'contacts/contact_create_update.html'
    form_class = ContatoForm
    model = Contato
    success_url = reverse_lazy('contacts:contato-list')

    def get_context_data(self, **kwargs):
        context = super(ContatoUpdate, self).get_context_data(**kwargs)

        endereco = ContatoEndereco.objects.filter(contato=self.object)
        telefones = [TelefoneSerializer(c.telefone).data for c in ContatoTelefone.objects.filter(contato=self.object)]

        if endereco:
            context['form_endereco'] = EnderecoForm(instance=endereco[0])
        else:
            context['form_endereco'] = EnderecoForm()

        context['formset_telefone'] = TelefoneFormSet(initial=telefones)
        context['formset_email'] = EmailFormSet()
        return context


#TODO: feito de maneira temporária para importar um arquivo de contatos exemplo.
class ContatoImport(View):
    template_name = 'contacts/contact_import.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        #from IPython import embed; embed()

        from contacts.models import Telefone, Email

        contatos_file = request.FILES['contatos_file']

        nome, instituicao, telefone, endereco, email = 0, 1, 2, 3, 4

        for line in contatos_file:
            line = line.decode("utf-8")
            print('>>>>', line)
            values = line.split(';')
            if not values[nome] or len(values) <= 4:
                continue

            print(values[nome])

            c = Contato(nome=values[nome], tipo='C', notas=values[endereco])
            t = Telefone(numero=values[telefone])
            e = Email(email=values[email])

            with transaction.atomic():
                c.save()
                t.save()
                e.save()

                ct = ContatoTelefone(contato=c, telefone=t)
                ce = ContatoEmail(contato=c, email=e)
                ct.save()
                ce.save()

        #form = self.form_class(request.POST)
       # if form.is_valid():
            # <process form cleaned data>
            #return HttpResponseRedirect('/success/')

        return render(request, self.template_name)

contacts/templates/contacts/contact_create_update.html
{% extends "layout_fixed.html" %}

{% block content_title %}
    <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Novo Contato</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="{% url 'dashboard:index' %}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
            <a href="{% url 'contacts:contato-list' %}" class="breadcrumb-item">Contatos</a>
            <span class="breadcrumb-item active">Novo</span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>

    </div>
{% endblock %}

{% block content %}




{% if form.errors %}
    {{ form.errors }}
{% endif %}

<div class="card">
    <div class="card-body">

        <form method="post">{% csrf_token %}
            <div class="form-group">
                <label>{{ form.nome.label }}:</label>
                {{ form.nome }}
                {{ form.nome.errors }}
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.tipo.label }}:</label>
                        {{ form.tipo }}
                        {{ form.tipo.errors }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.ocupacao.label }}:</label>
                        {{ form.ocupacao }}
                        {{ form.ocupacao.errors }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.instituicao.label }}:</label>
                        {{ form.instituicao }}
                        {{ form.instituicao.errors }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.departamento.label }}:</label>
                        {{ form.departamento }}
                        {{ form.departamento.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>{{ form.notas.label }}:</label>
                {{ form.notas }}
                {{ form.notas.errors }}
            </div>


            <fieldset>
                <legend>Telefones</legend>

                {# {{ formset_telefone }} #}
                <div class="row">
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_telefone.forms.0.numero }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_telefone.forms.1.numero }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_telefone.forms.2.numero }}
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>E-mails</legend>
                {# {{ formset_email }} #}
                <div class="row">
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_email.forms.0.email }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_email.forms.1.email }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="rounded py-2 px-3 mb-3">
                            {{ formset_email.forms.2.email }}
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                {# {{ form_endereco }} #}
                <legend>Endereço</legend>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.pais.label }}:</label>
                            {{ form_endereco.pais }}
                            {{ form_endereco.pais.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.estado.label }}:</label>
                            {{ form_endereco.estado }}
                            {{ form_endereco.estado.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.cidade.label }}:</label>
                            {{ form_endereco.cidade }}
                            {{ form_endereco.cidade.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.logradouro.label }}:</label>
                            {{ form_endereco.logradouro }}
                            {{ form_endereco.logradouro.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.numero.label }}:</label>
                            {{ form_endereco.numero }}
                            {{ form_endereco.numero.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.complemento.label }}:</label>
                            {{ form_endereco.complemento }}
                            {{ form_endereco.complemento.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{ form_endereco.cep.label }}:</label>
                            {{ form_endereco.cep }}
                            {{ form_endereco.cep.errors }}
                        </div>
                    </div>
                    
                </div>
            </fieldset>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Salvar<i class="icon-paperplane ml-2"></i></button>
            </div>

        <!--     <div>
              <input type="submit" value="Salvar" />
              <input type="hidden" name="next" value="{{ next }}" />
            </div> -->
        </form>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contato_list.html
{% extends "layout_fixed.html" %}

{% block content_title %}
    <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Lista de Contatos</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>
    <a href="{% url 'contacts:contato-create' %}">
        <button type="button" class="btn btn-primary"><i class="icon-user-plus mr-2"></i> Novo Contato</button>
    </a>
{% endblock %}

{% block breadcrumbs %}
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="{% url 'dashboard:index' %}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
            <span class="breadcrumb-item active">Contatos</span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>

    </div>
{% endblock %}

{% block breadcrumbs_right %}

{% endblock %}

{% block content %}

    <div class="card">
<!--         <div class="card-header header-elements-inline">
            <h5 class="card-title"></h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div> -->

        <div class="card-body">
            <form action="#">
                <div class="input-group mb-3">
                    <div class="form-group-feedback form-group-feedback-left">
                        <input type="text" class="form-control form-control-lg alpha-grey" placeholder="Pesquisar por contato">
                        <div class="form-control-feedback form-control-feedback-lg">
                            <i class="icon-search4 text-muted"></i>
                        </div>
                    </div>

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary btn-lg">Pesquisar</button>
                    </div>
                </div>

                <div class="d-md-flex align-items-md-center flex-md-wrap text-center text-md-left">
                    <ul class="list-inline list-inline-condensed mb-0">
                        <li class="list-inline-item dropdown">
                            <a href="#" class="btn btn-link text-default dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-stack2 mr-2"></i>
                                Todas as categorias
                            </a>

                            <div class="dropdown-menu">
                                <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Pessoais</a>
                                <a href="#" class="dropdown-item"><i class="icon-graduation"></i> Corporativos</a>
                            </div>
                        </li>
                        <!-- <li class="list-inline-item"><a href="#" class="btn btn-link text-default"><i class="icon-reload-alt mr-2"></i> Refine your search</a></li> -->
                    </ul>

                    <!-- <ul class="list-inline mb-0 ml-md-auto">
                        <li class="list-inline-item"><a href="#" class="btn btn-link text-default"><i class="icon-make-group mr-2"></i> Browse articles</a></li>
                        <li class="list-inline-item"><a href="#" class="btn btn-link text-default"><i class="icon-menu7 mr-2"></i> Advanced search</a></li>
                    </ul> -->
                </div>
            </form>
        </div>
    </div>



    <div class="card">
<!--         <div class="card-header header-elements-inline">
            <h5 class="card-title">Basic table</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div> -->

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="text-center"><input type="checkbox" class="form-check-input-styled" checked=""></th>
                        <th>Nome</th>
                        <th>Ocupação</th>
                        <th>Tipo</th>
                        <th>Instituição</th>
                        <th>Departamento</th>
                        <th>Telefones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" class="form-check-input-styled" checked="">
                            </td>
                            <td><a href="{% url 'contacts:contato-update' object.pk %}">{{ object.nome }}</a></td>
                            <td>{{ object.ocupacao }}</td>
                            <td>{{ object.get_tipo_display }}</td>
                            <td>{{ object.instituicao }}</td>
                            <td>{{ object.departamento }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

contacts/templates/contacts/index.htm
index.htm

contacts/templates/contacts/index.html
{% extends "base_generic.html" %}

{% block content %}
ll
    {% for object in object_list %}
        x
    {% endfor %}
{% endblock %}