bjorncrm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('interactions/', include('interaction.urls', namespace="interactions")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('xxxx/', TemplateView.as_view(template_name="layout_fixed.html")),
]

contacts/urls.py
from django.contrib import admin
from django.urls import path

from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.home, name='home'),
    path(r'contato/api/', views.ContatoApiList.as_view(), name='contato-api-list'),
    path(r'contato/api/<int:pk>/', views.ContatoApiDetail.as_view(), name='contato-api-details'),

    path(r'contato/', views.ContatoList.as_view(), name='contato-list'),
    path(r'contato/add/', views.ContatoCreate.as_view(), name='contato-create'),
    path(r'contato/update/<int:pk>/', views.ContatoUpdate.as_view(), name='contato-update'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name="dashboard/dashboard.html"), name='index'),
]

interaction/urls.py
from django.contrib import admin
from django.urls import path

from interaction import views

app_name = 'interaction'

urlpatterns = [
    # path(r'interacao/<int:pk>/', views.ContatoDetail.as_view(), name='interacao-details'),
    path(r'interacao/', views.InteracaoList.as_view(), name='interacao-list'),
    path(r'interacao/add/', views.InteracaoCreate.as_view(), name='interacao-create'),
    # path(r'interacao/update/<int:pk>/', views.ContatoUpdate.as_view(), name='interacao-update'),)
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = 'users'

urlpatterns = [
    # path(r'list/', views.UserList.as_view(), name='users-list'),
    # path(r'users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    # path(r'users/add/', views.UserCreate.as_view(), name='user-create'),
    # path(r'users/update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    # path('login', TemplateView.as_view(template_name='users/login_simple.html'))
    path(r'users/signup/', views.signup, name='signup'),
]

interaction/models.py
from django.db import models


class Interacao(models.Model):
    resumo = models.CharField(max_length=150, blank=True, null=True, verbose_name="Resumo")
    descricao = models.TextField(blank=True, null=True, verbose_name='Descrição')
    data = models.DateField(verbose_name='Data')
    horario = models.TimeField(blank=True, null=True, verbose_name='Horário')


class InteracaoContatos(models.Model):
    contato = models.ForeignKey('contacts.Contato', on_delete=models.CASCADE)
    interacao = models.ForeignKey(Interacao, on_delete=models.CASCADE)

interaction/forms.py
from django.forms import ModelForm
from interaction import models


class InteracaoForm(ModelForm):
    class Meta:
        model = models.Interacao
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

interaction/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from contacts.models import Contato
from interaction.forms import InteracaoForm
from interaction.models import Interacao, InteracaoContatos


class InteracaoList(ListView):
    model = Interacao

    #def get_context_data(self, **kwargs)


class InteracaoCreate(CreateView):
    template_name = 'interaction/interaction_create_update.html'
    form_class = InteracaoForm
    success_url = reverse_lazy('interaction:interacao-list')

    def get_context_data(self, **kwargs):
        context = super(InteracaoCreate, self).get_context_data(**kwargs)
        return context

interaction/templates/interaction/interacao_list.html
{% extends "layout_fixed.html" %}

{% block content_title %}
    <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Lista de Interações</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>
    <a href="{% url 'interactions:interacao-create' %}">
        <button type="button" class="btn btn-primary"><i class="icon-bubble-lines4 mr-2"></i> Nova Interação</button>
    </a>
{% endblock %}

{% block breadcrumbs %}
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="{% url 'dashboard:index' %}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
            <span class="breadcrumb-item active">Interações</span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>

    </div>
{% endblock %}

{% block breadcrumbs_right %}

{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-body">
            <form action="#">
                <div class="input-group mb-3">
                    <div class="form-group-feedback form-group-feedback-left">
                        <input type="text" class="form-control form-control-lg alpha-grey" placeholder="Pesquisar por Interação">
                        <div class="form-control-feedback form-control-feedback-lg">
                            <i class="icon-search4 text-muted"></i>
                        </div>
                    </div>

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary btn-lg">Pesquisar</button>
                    </div>
                </div>

                <div class="d-md-flex align-items-md-center flex-md-wrap text-center text-md-left">
                    <ul class="list-inline list-inline-condensed mb-0">
                        <li class="list-inline-item dropdown">
                            <a href="#" class="btn btn-link text-default dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-stack2 mr-2"></i>
                                Todas as categorias
                            </a>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    </div>



    <div class="card">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Interação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.data|date:"Y-m-d" }}, {{ object.horario|default:"" }}</td>
                            <td>
                                {% if object.resumo %}
                                    {{ object.resumo }}
                                {% else %}
                                    {{ object.descricao|truncatechars:150 }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

interaction/templates/interaction/interaction_create_update.html
{% extends "layout_fixed.html" %}
{% load static %}

{% block head %}
<link href="{% static 'assets/css/components.min.css' %}" rel="stylesheet" type="text/css">
{# <link href="{% static 'global_assets/js/plugins/forms/tags/tagsinput.min.js' %}"></script>#}
<script src="{% static 'global_assets/js/plugins/forms/tags/tagsinput.min.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/forms/tags/tokenfield.min.js' %}"></script>
<script src="{% static 'global_assets/js/demo_pages/form_tags_input.js' %}"></script>


    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
    <script src="{% static 'js/typeahead.bundle.js' %}"></script>
    <!-- <script type="text/javascript" src="//netsh.pp.ua/upwork-demo/1/js/typeahead.js"></script> -->

    <script type="text/javascript">

        function initAutocompletion() {
            var $this = $('#the-basics .typeahead');
            var urlPrefetch = '{% url "contacts:contato-api-list" %}?format=json'; //$this.data("autocomplete-prefetch-url");
            var prefetch;

            pref = {
                url: urlPrefetch,
                filter: filter
            };

            var bloodHound = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                limit: 10,
                prefetch: pref
            });

            bloodHound.clearPrefetchCache();
            bloodHound.initialize();

            $this
                .typeahead('destroy')
                .typeahead({
                    //hint: true,
                    //highlight: true,
                    minLength: 1
                },
                {
                    displayKey: 'value',
                    source: bloodHound.ttAdapter()
                });
        };

        function filter(list) {
            return $.map(list, function (v) { return { value: v['nome'] }; });
        }

        function add_contato(is_contato, contato) {
            if (is_contato)
                color = 'pessoa_contato'
            else
                color = 'pessoa_nao_contato'

            $('#div_pessoas').append('<div class="pessoa ' + color + '">' + contato + '</div>')
            $('.typeahead').typeahead('val','');
        }

        $(function() {
        // $("input.doctor").typeahead({
        //   name: "doctor",
        //   remote: "doctor.php?query=%QUERY"
        // });









// var substringMatcher = function(strs) {
//   return function findMatches(q, cb) {
//     var matches, substringRegex;

//     // an array that will be populated with substring matches
//     matches = [];

//     // regex used to determine if a string contains the substring `q`
//     substrRegex = new RegExp(q, 'i');

//     // iterate through the pool of strings and for any string that
//     // contains the substring `q`, add it to the `matches` array
//     $.each(strs, function(i, str) {
//       if (substrRegex.test(str)) {
//         matches.push(str);
//       }
//     });

//     cb(matches);
//   };
// };

// var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
//   'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
//   'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
//   'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
//   'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
//   'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
//   'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
//   'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
//   'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
// ];

// $('#the-basics .typeahead').typeahead({
//   hint: true,
//   highlight: true,
//   minLength: 1
// },
// {
//   name: 'states',
//   source: substringMatcher(states)
// });


            initAutocompletion();


            $('.typeahead').bind('typeahead:select', function(ev, suggestion) {
              //console.log('Selection: ' + suggestion);
              add_contato(true, $('input.typeahead.tt-input').val());
            });

          $('.typeahead').keydown(function(e) {
            var keyCode = e.keyCode || e.which;

            if(keyCode == 13)
            {
              e.preventDefault();
              //alert($('input.typeahead.tt-input').val());
              // alert($('.typeahead').val());
              // alert($('.typeahead').typeahead('val'))
              // alert($('.typeahead tt-input').typeahead('val'))
              add_contato(false, $('input.typeahead.tt-input').val());


              //$(this).typeahead('close');
              //alert($('input.typeahead.tt-input').val());
              //alert($('input.typeahead.tt-input').val());
              //Code to imitate keypress of Tab key
            }
          });

          // $('.typeahead').bind('typeahead:close', function(ev, xxx){
          //       // $('input.typeahead').val('');
          //       // $('input.typeahead.tt-input').val('');
          //       // alert('typeahead:close')
          //       // e.preventDefault();
          //       // return false;
          // })
            // $('.typeahead').bind('typeahead:closed', function () {
            //     $(this).val("");
            // });




            // $('.typeahead').bind('typeahead:autocompleted', function(ev, suggestion) {
            //   console.log('Autocompleted: ' + suggestion);
            // });

        });


    </script>

    <style type="text/css">
    .tt-query {
      -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
         -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
              box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    }

    .tt-hint {
      color: #999
    }

    .tt-menu {    /* used to be tt-dropdown-menu in older versions */
      width: 422px;
      margin-top: 4px;
      padding: 4px 0;
      background-color: #fff;
      border: 1px solid #ccc;
      border: 1px solid rgba(0, 0, 0, 0.2);
      -webkit-border-radius: 4px;
         -moz-border-radius: 4px;
              border-radius: 4px;
      -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
         -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
              box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .tt-suggestion {
      padding: 3px 20px;
      line-height: 24px;
    }

    .tt-suggestion.tt-cursor,.tt-suggestion:hover {
      color: #fff;
      background-color: #0097cf;

    }

    .tt-suggestion p {
      margin: 0;
    }

    .pessoa_contato {
        background: #ff0;
    }

    .pessoa_nao_contato {
        background: #ffc;
    }
    </style>

{% endblock %}


{% block content_title %}
    <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Nova Interação</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="{% url 'dashboard:index' %}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
            <a href="{% url 'interactions:interacao-list' %}" class="breadcrumb-item">Interações</a>
            <span class="breadcrumb-item active">Nova</span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>

    </div>
{% endblock %}

{% block content %}




{% if form.errors %}
    {{ form.errors }}
{% endif %}

<div class="card">
    <div class="card-body">
            <form method="post">{% csrf_token %}

            <div id="the-basics" class="form-group">
                <label>Envolvidos:</label>
                <input class="typeahead form-control" type="text" placeholder="Pessoas">
            </div>

          <div id="div_pessoas" class="form-group">
          </div>

            <div class="form-group">
                <label>Tags:</label>
                <select multiple="" data-placeholder="Enter tags" class="form-control form-control-select2-icons select2-hidden-accessible" data-fouc="" tabindex="-1" aria-hidden="true">
                    <optgroup label="Services">
                        <option value="wordpress2" data-icon="wordpress2">Wordpress</option>
                        <option value="tumblr2" data-icon="tumblr2">Tumblr</option>
                        <option value="stumbleupon" data-icon="stumbleupon">Stumble upon</option>
                        <option value="pinterest2" data-icon="pinterest2">Pinterest</option>
                        <option value="lastfm2" data-icon="lastfm2">Lastfm</option>
                    </optgroup>
                    <optgroup label="File types">
                        <option value="pdf" data-icon="file-pdf">PDF</option>
                        <option value="word" data-icon="file-word">Word</option>
                        <option value="excel" data-icon="file-excel">Excel</option>
                        <option value="openoffice" data-icon="file-openoffice">Open office</option>
                    </optgroup>
                    <optgroup label="Browsers">
                        <option value="chrome" data-icon="chrome" selected="">Chrome</option>
                        <option value="firefox" data-icon="firefox" selected="">Firefox</option>
                        <option value="safari" data-icon="safari">Safari</option>
                        <option value="opera" data-icon="opera">Opera</option>
                        <option value="IE" data-icon="IE">IE</option>
                    </optgroup>
                </select><span class="select2 select2-container select2-container--default select2-container--focus" dir="ltr" style="width: 100%;"><span class="selection"><span class="select2-selection select2-selection--multiple" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1"><ul class="select2-selection__rendered"><li class="select2-selection__choice" title="Chrome"><span class="select2-selection__choice__remove" role="presentation">×</span><i class="icon-chrome"></i>Chrome</li><li class="select2-selection__choice" title="Firefox"><span class="select2-selection__choice__remove" role="presentation">×</span><i class="icon-firefox"></i>Firefox</li><li class="select2-search select2-search--inline"><input class="select2-search__field" type="search" tabindex="0" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" role="textbox" aria-autocomplete="list" placeholder="" style="width: 0.75em;"></li></ul></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            </div>

            <div class="form-group">
                <label>{{ form.resumo.label }}:</label>
                {{ form.resumo }}
                {{ form.resumo.errors }}
            </div>

            <div class="form-group">
                <label>{{ form.descricao.label }}:</label>
                {{ form.descricao }}
                {{ form.descricao.errors }}
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.data.label }}:</label>
                        {{ form.data }}
                        {{ form.data.errors }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ form.horario.label }}:</label>
                        {{ form.horario }}
                        {{ form.horario.errors }}
                    </div>
                </div>
            </div>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Salvar<i class="icon-paperplane ml-2"></i></button>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>

        </form>
    </div>
</div>
{% endblock %}