bjorncrm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('interactions/', include('interaction.urls', namespace="interactions")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('xxxx/', TemplateView.as_view(template_name="layout_fixed.html")),
]

contacts/urls.py
from django.contrib import admin
from django.urls import path

from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.home, name='home'),
    path(r'contato/api/', views.ContatoApiList.as_view(), name='contato-api-list'),
    path(r'contato/api/<int:pk>/', views.ContatoApiDetail.as_view(), name='contato-api-details'),

    path(r'contato/', views.ContatoList.as_view(), name='contato-list'),
    path(r'contato/add/', views.ContatoCreate.as_view(), name='contato-create'),
    path(r'contato/update/<int:pk>/', views.ContatoUpdate.as_view(), name='contato-update'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name="dashboard/dashboard.html"), name='index'),
]

interaction/urls.py
from django.contrib import admin
from django.urls import path

from interaction import views

app_name = 'interaction'

urlpatterns = [
    # path(r'interacao/<int:pk>/', views.ContatoDetail.as_view(), name='interacao-details'),
    path(r'interacao/', views.InteracaoList.as_view(), name='interacao-list'),
    path(r'interacao/add/', views.InteracaoCreate.as_view(), name='interacao-create'),
    # path(r'interacao/update/<int:pk>/', views.ContatoUpdate.as_view(), name='interacao-update'),)
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = 'users'

urlpatterns = [
    # path(r'list/', views.UserList.as_view(), name='users-list'),
    # path(r'users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    # path(r'users/add/', views.UserCreate.as_view(), name='user-create'),
    # path(r'users/update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    # path('login', TemplateView.as_view(template_name='users/login_simple.html'))
    path(r'users/signup/', views.signup, name='signup'),
]

templates/base_generic.html
<!doctype html>
<html>
    <head>
        <title>Bjorn CRM</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

        {% block head %}
        {% endblock head %}
    </head>
    <body>
        <div style="background: #F00;width:100%;height:5px;margin:0px;padding:0px"></div>

        <div>
            <a href="{% url 'contacts:contato-list' %}">Contatos</a> &nbsp;|&nbsp;
            <a href="{% url 'contacts:contato-create' %}">+ Contato</a> &nbsp;|&nbsp;
            <a href="{% url 'interactions:interacao-list' %}">Interações</a> &nbsp;|&nbsp;
            <a href="{% url 'interactions:interacao-create' %}">+ Interação</a> &nbsp;|&nbsp;
        </div>


        <h1>{{page_name}}</h1>

        <div style="margin-left:auto;margin-right:auto; background:#0f0; width: 80%">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/layout_fixed.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>BJORN - CRM</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="{% static 'global_assets/css/icons/icomoon/styles.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/bootstrap_limitless.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/layout.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/components.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/colors.min.css' %}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
	<script src="{% static 'global_assets/js/main/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'global_assets/js/plugins/loaders/blockui.min.js' %}"></script>
	<script src="{% static 'global_assets/js/plugins/ui/perfect_scrollbar.min.js' %}"></script>
	<script src="{% static 'global_assets/js/demo_pages/layout_fixed_sidebar_custom.js' %}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="{% static 'assets/js/app.js' %}"></script>
	<!-- /theme JS files -->
	{% block head %}{% endblock %}
</head>

<body class="navbar-top">

	<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-dark fixed-top">
		<div class="navbar-brand">
			<a href="{% url 'dashboard:index' %}" class="d-inline-block">
				<img src="{% static 'global_assets/images/logo_light.png' %}" alt="">
			</a>
		</div>

		<div class="d-md-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>
			</ul>

			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link">
						Text link
					</a>
				</li>

				<li class="nav-item dropdown">
					<a href="#" class="navbar-nav-link">
						<i class="icon-bell2"></i>
						<span class="d-md-none ml-2">Notifications</span>
						<span class="badge badge-mark border-white ml-auto ml-md-0"></span>
					</a>
				</li>

				<li class="nav-item dropdown dropdown-user">
					<a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
						<img src="{% static 'global_assets/images/image.png' %}" class="rounded-circle mr-2" height="34" alt="">
						<span>Victoria</span>
					</a>

					<div class="dropdown-menu dropdown-menu-right">
						<a href="#" class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
						<a href="#" class="dropdown-item"><i class="icon-coins"></i> My balance</a>
						<a href="#" class="dropdown-item"><i class="icon-comment-discussion"></i> Messages <span class="badge badge-pill bg-blue ml-auto">58</span></a>
						<div class="dropdown-divider"></div>
						<a href="#" class="dropdown-item"><i class="icon-cog5"></i> Account settings</a>
						<a href="#" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<!-- /main navbar -->


	<!-- Page content -->
	<div class="page-content">

		<!-- Main sidebar -->
		<div class="sidebar sidebar-dark sidebar-main sidebar-fixed sidebar-expand-md">

			<!-- Sidebar mobile toggler -->
			<div class="sidebar-mobile-toggler text-center">
				<a href="#" class="sidebar-mobile-main-toggle">
					<i class="icon-arrow-left8"></i>
				</a>
				Navigation
				<a href="#" class="sidebar-mobile-expand">
					<i class="icon-screen-full"></i>
					<i class="icon-screen-normal"></i>
				</a>
			</div>
			<!-- /sidebar mobile toggler -->


			<!-- Sidebar content -->
			<div class="sidebar-content">

				<!-- User menu -->
<!-- 				<div class="sidebar-user">
					<div class="card-body">
						<div class="media">
							<div class="mr-3">
								<a href="#"><img src="{% static 'global_assets/images/image.png' %}" width="38" height="38" class="rounded-circle" alt=""></a>
							</div>

							<div class="media-body">
								<div class="media-title font-weight-semibold">Victoria Baker</div>
								<div class="font-size-xs opacity-50">
									<i class="icon-pin font-size-sm"></i> &nbsp;Santa Ana, CA
								</div>
							</div>

							<div class="ml-3 align-self-center">
								<a href="#" class="text-white"><i class="icon-cog3"></i></a>
							</div>
						</div>
					</div>
				</div> -->
				<!-- /user menu -->


				<!-- Main navigation -->
				<div class="card card-sidebar-mobile">
					<ul class="nav nav-sidebar" data-nav-type="accordion">

						<!-- Main -->
						<!-- <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li> -->
						<li class="nav-item">
							<a href="{% url 'dashboard:index' %}" class="nav-link">
								<i class="icon-home4"></i>
								<span>Dashboard</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'contacts:contato-list' %}" class="nav-link">
								<i class="icon-notebook"></i>
								<span>Contatos</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'interactions:interacao-list' %}" class="nav-link">
								<i class="icon-bubble-lines4"></i>
								<span>Interações</span>
							</a>
						</li>

<!-- 						<li class="nav-item nav-item-submenu nav-item-expanded nav-item-open">
							<a href="#" class="nav-link"><i class="icon-stack"></i> <span>Starter kit</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Starter kit">
								<li class="nav-item"><a href="../seed/layout_nav_horizontal.html" class="nav-link">Horizontal navigation</a></li>
								<li class="nav-item"><a href="../seed/sidebar_none.html" class="nav-link">No sidebar</a></li>
								<li class="nav-item"><a href="../seed/sidebar_main.html" class="nav-link">1 sidebar</a></li>
								<li class="nav-item nav-item-submenu">
									<a href="#" class="nav-link">2 sidebars</a>
									<ul class="nav nav-group-sub">
										<li class="nav-item"><a href="../seed/sidebar_secondary.html" class="nav-link">Secondary sidebar</a></li>
										<li class="nav-item"><a href="../seed/sidebar_right.html" class="nav-link">Right sidebar</a></li>
									</ul>
								</li>
								<li class="nav-item nav-item-submenu">
									<a href="#" class="nav-link">3 sidebars</a>
									<ul class="nav nav-group-sub">
										<li class="nav-item"><a href="../seed/sidebar_right_hidden.html" class="nav-link">Right sidebar hidden</a></li>
										<li class="nav-item"><a href="../seed/sidebar_right_visible.html" class="nav-link">Right sidebar visible</a></li>
									</ul>
								</li>
								<li class="nav-item nav-item-submenu">
									<a href="#" class="nav-link">Content sidebars</a>
									<ul class="nav nav-group-sub">
										<li class="nav-item"><a href="../seed/sidebar_content_left.html" class="nav-link">Left sidebar</a></li>
										<li class="nav-item"><a href="../seed/sidebar_content_right.html" class="nav-link">Right sidebar</a></li>
									</ul>
								</li>
								<li class="nav-item"><a href="../seed/layout_boxed.html" class="nav-link">Boxed layout</a></li>
								<li class="nav-item-divider"></li>
								<li class="nav-item"><a href="../seed/navbar_fixed_main.html" class="nav-link">Fixed main navbar</a></li>
								<li class="nav-item"><a href="../seed/navbar_fixed_secondary.html" class="nav-link">Fixed secondary navbar</a></li>
								<li class="nav-item"><a href="../seed/navbar_fixed_both.html" class="nav-link">Both navbars fixed</a></li>
								<li class="nav-item"><a href="../seed/layout_fixed.html" class="nav-link active">Fixed layout</a></li>
							</ul>
						</li>
						<li class="nav-item">
							<a href="../full/changelog.html" class="nav-link">
								<i class="icon-list-unordered"></i>
								<span>Changelog</span>
								<span class="badge bg-blue-400 align-self-center ml-auto">2.1</span>
							</a>
						</li> -->
						<!-- /main -->

					</ul>
				</div>
				<!-- /main navigation -->

			</div>
			<!-- /sidebar content -->

		</div>
		<!-- /main sidebar -->


		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Page header -->
			<div class="page-header page-header-light">
				<div class="page-header-content header-elements-md-inline">
					{% block content_title %}

					{% endblock %}

<!-- 					<div class="page-title d-flex">
						<h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Starters</span> - Fixed Layout</h4>
						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>

					<div class="header-elements d-none">
						<a href="#" class="btn btn-labeled btn-labeled-right bg-primary">Button <b><i class="icon-menu7"></i></b></a>
					</div> -->
				</div>

				<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
					{% block breadcrumbs %}
					{% endblock %}
<!-- 					<div class="d-flex">
						<div class="breadcrumb">
							<a href="index.html" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
							<a href="#" class="breadcrumb-item">Link</a>
							<span class="breadcrumb-item active">Current</span>
						</div>

						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div> -->

					<div class="header-elements d-none">
						{% block breadcrumbs_right %}
						{% endblock %}
<!-- 						<div class="breadcrumb justify-content-center">
							<a href="#" class="breadcrumb-elements-item">
								Link
							</a>

							<div class="breadcrumb-elements-item dropdown p-0">
								<a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
									Dropdown
								</a>

								<div class="dropdown-menu dropdown-menu-right">
									<a href="#" class="dropdown-item">Action</a>
									<a href="#" class="dropdown-item">Another action</a>
									<a href="#" class="dropdown-item">One more action</a>
									<div class="dropdown-divider"></div>
									<a href="#" class="dropdown-item">Separate action</a>
								</div>
							</div>
						</div> -->
					</div>
				</div>
			</div>
			<!-- /page header -->


			<!-- Content area -->
			<div class="content">
				{% block content %}
				{% endblock %}


			</div>
			<!-- /content area -->


			<!-- Footer -->
			<div class="navbar navbar-expand-lg navbar-light">
				<div class="text-center d-lg-none w-100">
					<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
						<i class="icon-unfold mr-2"></i>
						Footer
					</button>
				</div>

				<div class="navbar-collapse collapse" id="navbar-footer">
					{% block footer %}
					{% endblock %}
<!-- 					<span class="navbar-text">
						&copy; 2015 - 2018. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
					</span> -->

<!-- 					<ul class="navbar-nav ml-lg-auto">
						<li class="nav-item">
							<a href="#" class="navbar-nav-link">Text link</a>
						</li>

						<li class="nav-item">
							<a href="#" class="navbar-nav-link">
								<i class="icon-lifebuoy"></i>
							</a>
						</li>

						<li class="nav-item">
							<a href="https://themeforest.net/item/limitless-responsive-web-application-kit/13080328?ref=kopyov" class="navbar-nav-link font-weight-semibold">
								<span class="text-pink-400">
									<i class="icon-cart2 mr-2"></i>
									Purchase
								</span>
							</a>
						</li>
					</ul> -->
				</div>
			</div>
			<!-- /footer -->

		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->

</body>
</html>

templates/layout_nonavbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BJORN CRM</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{% static 'global_assets/css/icons/icomoon/styles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/bootstrap_limitless.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/layout.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/components.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/colors.min.css' %}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
    <script src="{% static 'global_assets/js/main/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'global_assets/js/plugins/loaders/blockui.min.js' %}"></script>
    <script src="{% static 'global_assets/js/plugins/ui/perfect_scrollbar.min.js' %}"></script>
    <script src="{% static 'global_assets/js/demo_pages/layout_fixed_sidebar_custom.js' %}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="{% static 'assets/js/app.js' %}"></script>
    <!-- /theme JS files -->
    {% block head %}{% endblock %}
</head>

<body>

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            {% block content %}

            {% endblock %}

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</body>
</html>